#!/bin/bash

# shellcheck disable=SC2034

remote="$1"     # name of remote e.g. "origin"
url="$2"        # url of remote e.g. "git@github.com:gurpreetatwal/dotfiles

if [[ ! "$url" =~ "smartcar" ]]; then
  exit 0
fi

current_branch=false
ack=false

warn() {
  if [[ "$ack" != "true" && "master" = "$1" ]]; then
    printf "\e[1;31m[WARNING]\e[0m\n"
    printf "\e[1;31m[WARNING]\e[0m  You're about to push master, are you sure you want to do this? [YES/no]\n"
    printf "\e[1;31m[WARNING]\e[0m\n"
    read -r < /dev/tty
    if [ "$REPLY" != 'YES' ]; then exit 1; fi
    ack=true
  fi
}

while read -r localname localhash remotename remotehash; do
  warn "$(echo "$remotename" | awk -F '/' '{print $3}')"
done

warn "$(git symbolic-ref HEAD | awk -F '/' '{print $3}')"
