#!/usr/bin/env bash

view() {
  pygmentize -f 16m -O style=paraiso-dark "$1"
}

json() {
  # shellcheck disable=SC2005  # echo with command substitution is intentional to capture output
  echo "$(jq --sort-keys . "$1")" | tee "$1"
}

screenshot() {
  local 'file';
  file="/tmp/screenshot-$(date '+%Y-%m-%d_%H-%M-%S').png"
  import "$file"
  xclip -selection clipboard -target image/png -i < "${file}"
}

clippipe() {
  xclip -out -selection clipboard | "$@" | xclip -in -selection clipboard
}

escapechars() {
  sed 's/[^A-Za-z0-9-]/\\\0/g'
}

human_time() {
  if [ ${#1} -gt 10 ]; then
    ## milliseconds
    date -d "@${1:0:10}.${1:10}"
  else
    ## seconds
    date -d "@$1"
  fi
}

android_screenshot() {
  adb exec-out screencap -p | xclip -t image/png -sel clip
}

# fasd
if [ "$(command -v fasd)" ]; then
  # taken from: https://github.com/clvv/fasd/blob/master/fasd#L89
  fasd_cd() {
    local '_fasd_ret';
    _fasd_ret="$(fasd -e 'printf %s' "$@")"
    [ -z "$_fasd_ret" ] && return
    [ -d "$_fasd_ret" ] && cd "$_fasd_ret" || printf %s\\n "$_fasd_ret"
  }
fi

# fasd + fzf = <3
if [ "$(command -v fzf)" ] && [ "$(command -v fasd)" ]; then

  # fasd & fzf change directory - jump using `fasd` if given argument, filter output of `fasd` using `fzf` else
  function z {
    [ $# -gt 0 ] && fasd_cd -d "$@" && return
    local 'dir'
    dir="$(fasd -Rdl "$1" | sed "s:$HOME:~:" | fzf -1 -0 --no-sort --no-multi | sed "s:~:$HOME:")" && cd "$dir" || return 1
  }

  # fasd & fzf open vim - open best matched file using `fasd` if given argument, filter output of `fasd` using `fzf` else
  function v {
    [ $# -gt 0 ] && fasd -f -e "$EDITOR" "$@" && return
    local 'file'
    file="$(fasd -Rfl "$1" | sed "s:$HOME:~:" | fzf -0 --no-sort --multi | sed "s:~:$HOME:")" && "$EDITOR" "$file" || return 1
  }

  # fasd & fzf open vim - open best matched file using `fasd` if given argument, filter output of `fasd` using `fzf` else
  function o {
    [ $# -gt 0 ] && fasd -a -e "xdg-open" "$@" && return
    local 'file'
    file="$(fasd -Ral "$1"  | sed "s:$HOME:~:" | fzf -0 --no-sort --no-multi | sed "s:~:$HOME:")" && "xdg-open" "$file" || return 1
  }

fi

#  Jumps to temp directory or if given a name, creates that directory and jumps to it
temp() {
  local 'whereto';
  whereto="$HOME/temp"
  if [[ "$#" == 1 ]]; then
    whereto="$whereto/$1"
    mkdir "$whereto"
  fi
  cd "$whereto" || exit
}

# Switch between different development environments
prod() {
  export NODE_ENV='production'
}

qa() {
  export NODE_ENV='qa'
}

dev() {
  export NODE_ENV='development'
  unset AWS_PROFILE
}

# Pause / unpause notifications
DND_FILE="/tmp/$USER.do-not-disturb"
DND_PS1="\e[38;2;255;255;0m⎇  \e[0m"

if [ -f "$DND_FILE" ]; then
  export SPACESHIP_CHAR_PREFIX="$DND_PS1"
fi

dnd() {
  if [ -f "$DND_FILE" ]; then
    unset SPACESHIP_CHAR_PREFIX
    killall -SIGUSR2 dunst
    rm -f "$DND_FILE"
  else
    export SPACESHIP_CHAR_PREFIX="$DND_PS1"
    killall -SIGUSR1 dunst
    touch "$DND_FILE"
  fi
}
