source ~/dotfiles/shell/commonrc

fpath=("$HOME/.zfunctions" "$XDG_DATA_HOME/zsh-completions/src" $fpath)

# Set up the prompt

export SPACESHIP_DOCKER_SHOW=false      # don't show docker version in the prompt
export SPACESHIP_PACKAGE_SHOW=false     # don't show package version in the prompt
autoload -Uz promptinit
promptinit
prompt spaceship

setopt histignorealldups sharehistory

# Keep 10000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

## Completions
autoload -Uz compinit && compinit
autoload -U +X bashcompinit && bashcompinit

# terraform
test -f "$HOME/bin/terraform" && complete -o nospace -C "$HOME/bin/terraform" terraform

## Options
### Changing Directories
# If a command is issued that can’t be executed as a normal command, and the command is the name of a directory, cd to that directory
setopt autocd
# Make cd push the old directory onto the directory stack.
setopt auto_pushd

### Input/Output
# Try to correct the spelling of commands
setopt correct
# Try to correct the spelling of all arguments in a line
setopt correct_all


zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Update terminal title to show current directory and running command
preexec () {
 print -Pn "\e]0;[`pwd | sed "s:$HOME:~:"`]: $1\a"
}

# Allow for local configuration
if [ -e "$HOME/.zshrc.local" ]; then
  source "$HOME/.zshrc.local"
fi
