name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Run shellcheck
        run: shellcheck --exclude=SC1090,SC1091 "install/run-helper" "install/helpers.sh" shell/aliases shell/commonrc shell/functions shell/profile
